spring:
  profile:
  datasource:
    driver-class-name: org.h2.Driver
    username: "sa"
    password: ""
  h2:
    console:
      enabled: true
      settings:
        trace: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  profiles:
    active: firebase
server:
  port: 8090


environments:
  rss: "http://ec2-34-203-75-254.compute-1.amazonaws.com:10001"
  secret: "haishdoijocewpok"

cors:
  allowed-origins:
    - http://localhost:8080
    - http://localhost:8090
    - http://localhost:3000
    - http://ec2-34-204-205-63.compute-1.amazonaws.com:8090
    - http://ec2-34-204-205-63.compute-1.amazonaws.com:10000
    - http://ec2-34-204-205-63.compute-1.amazonaws.com:80
  allowed-methods:
    - OPTIONS
    - GET
    - PUT
    - POST
    - PATCH
    - DELETE
  allowed-headers:
    - Accept
    - Authorization
    - Content-Type
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Methods
    - Access-Control-Allow-Headers
    - Access-Control-Expose-Headers
  exposed-headers:
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Expose-Headers
    - Content-Type
    - Authorization
    - Accept
  allow-credentials: true
